# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NeteaseIM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NeteaseIM
  pod 'MessageKit', '~> 1.0.0-beta.1'
  pod 'NIMSDK'
  pod 'Kingfisher', '~> 4.0'
  pod 'SnapKit', '~> 4.0.0'

  target 'NeteaseIMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NeteaseIMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
